---
- hosts: all
  sudo: yes
  vars:
    vagrant_path: "/home/vagrant"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install general packages
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - htop
        - curl

    - name: Add python3.5 repository
      apt_repository: repo='ppa:fkrull/deadsnakes' state=present
      sudo: yes

    - name: Install python3.5
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - python3.5

    - name: Install setuptools and pip3
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - python-setuptools
        - python3-pip

    - name: Install python3 dev packages
      apt: name={{item}} state=latest
      sudo: yes
      with_items:
        - python3.5-dev
        - libpq-dev
        - libffi-dev
        - libtiff5-dev
        - libjpeg8-dev
        - zlib1g-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libwebp-dev
        - tcl8.6-dev
        - tk8.6-dev
        - python-tk

    - name: Install virtualenv with pip
      pip: name=virtualenv executable=pip3

    - name: Make virtualenv
      shell: virtualenv -p /usr/bin/python3.5 /.virtualenvs/app
      sudo: yes

    - name: Making vagrant user the owner of /.virtualenvs dir
      shell: chown -R vagrant /.virtualenvs
      sudo: yes

    - name: Add repository with the latest version of nodejs
      shell: curl --silent --location https://deb.nodesource.com/setup_5.x | bash -
      sudo: yes

    - name: Install nodejs and npm
      apt: name={{item}} state=latest
      sudo: yes
      with_items:
        - nodejs

    - name: Add symbolic link to nodejs as node
      shell: sudo ln -s /usr/bin/nodejs /usr/bin/node
      ignore_errors: yes

    - name: Add PostgreSQL repository
      apt_repository: repo="deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" state=present

    - name: Fetch PostgreSQL repository key
      shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Install PostgreSQL
      apt: name={{item}}
      with_items:
          - postgresql

    - name: Install PostgreSQL stuff
      apt: name={{item}}
      with_items:
        - postgresql-contrib
        - python-psycopg2

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=restarted enabled=yes

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: ads-dev
    dbuser: admin
    dbpassword: homm1994
    test_dbname: ads-dev-test
    test_dbuser: qabot
    test_dbpassword: homm1994

  tasks:
    - name: Create db
      postgresql_db: name={{ dbname }}

    - name: Create user
      postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ dbpassword }} role_attr_flags=SUPERUSER priv=ALL

    - name: Create test db
      postgresql_db: name={{ test_dbname }}

    - name: Create test user
      postgresql_user: db={{ test_dbname }} name={{ test_dbuser }} password={{ test_dbpassword }} role_attr_flags=SUPERUSER priv=ALL
