"""Unique index removed for advert_orders.heading_picture

Revision ID: 079962ab0ebc
Revises: 3334358ba20b
Create Date: 2016-09-26 13:23:47.877344

"""

# revision identifiers, used by Alembic.
revision = '079962ab0ebc'
down_revision = '3334358ba20b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advert_orders_heading_picture_key', 'advert_orders', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('advert_orders_heading_picture_key', 'advert_orders', ['heading_picture'])
    ### end Alembic commands ###
