"""advert_orders table has been implemented

Revision ID: 3334358ba20b
Revises: fd1072bd3817
Create Date: 2016-09-22 15:09:51.697044

"""

# revision identifiers, used by Alembic.
revision = '3334358ba20b'
down_revision = 'fd1072bd3817'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading_picture', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), server_default='1', nullable=False),
    sa.Column('follow_url_link', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['ad_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follow_url_link'),
    sa.UniqueConstraint('heading_picture')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advert_orders')
    ### end Alembic commands ###
