"""clicks table

Revision ID: 8dfab716a234
Revises: f9046868fb5e
Create Date: 2016-11-22 14:55:57.428525

"""

# revision identifiers, used by Alembic.
revision = '8dfab716a234'
down_revision = 'f9046868fb5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clicks')
    ### end Alembic commands ###
