"""views model

Revision ID: b5fcaef7f906
Revises: 8dfab716a234
Create Date: 2016-12-05 22:41:46.925223

"""

# revision identifiers, used by Alembic.
revision = 'b5fcaef7f906'
down_revision = '8dfab716a234'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views')
    ### end Alembic commands ###
