"""Placement model implemented

Revision ID: f60a9cf48d34
Revises: 079962ab0ebc
Create Date: 2016-10-06 12:09:34.670853

"""

# revision identifiers, used by Alembic.
revision = 'f60a9cf48d34'
down_revision = '079962ab0ebc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['advert_orders.id'], ),
    sa.ForeignKeyConstraint(['placer_id'], ['ad_placers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placer_id', 'order_id', name='placements_placer_order_uc')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    ### end Alembic commands ###
