"""Type in  column name fixed

Revision ID: fd1072bd3817
Revises: 8d97c9dd3ee1
Create Date: 2016-08-01 11:08:24.589960

"""

# revision identifiers, used by Alembic.
revision = 'fd1072bd3817'
down_revision = '8d97c9dd3ee1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_placers', sa.Column('website', sa.String(), nullable=False))
    op.drop_column('ad_placers', 'webiste')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_placers', sa.Column('webiste', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ad_placers', 'website')
    ### end Alembic commands ###
